version: '2'
services:
  crawler:
    build: ./crawler
    volumes:
      - ./crawler:/crawler

  web:
    build: ./web_app
    ports:
      - "5000:5000"
    volumes:
      - ./web_app:/web_app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always
